#include "DgViewer.h"

bool show_window_model_property = true;
void OpenProperty();

void ShowWindowModelProperty(bool* p_open)
{

	ImGuiWindowFlags window_flags = 0;

	// 속성 윈도우를 생성하고, collapsed된 상태라면 바로 리턴한다.
	if (!ImGui::Begin("Property", nullptr, window_flags))
	{
		ImGui::End();
		return;
	}
	OpenProperty();	
	ImGui::End();
}

void OpenProperty() {
	const int NumIcons = 9;

	const char* icon_files[NumIcons] = {
		".\\res\\icons\\Union-A-B.png",
		".\\res\\icons\\Intersection-A-B.png",
		".\\res\\icons\\Difference-A-B.png",
		".\\res\\icons\\create_crv.png",
		".\\res\\icons\\create_polyline.png",
		".\\res\\icons\\create_linear.png",
		".\\res\\icons\\create_Bezier_crv.png",
		".\\res\\icons\\sculpt_add.png",
		".\\res\\icons\\sculpt_remove.png"
	};

	static GLuint icon_tex_id[NumIcons] = { 0 };
	if (icon_tex_id[0] == 0)
	{
		for (int i = 0; i < NumIcons; ++i)
			icon_tex_id[i] = DgUtil::loadTexture2D(icon_files[i]);
	}

	if (ImGui::CollapsingHeader("Boolean"))
	{
		// 선택된 볼륨 수집
		std::vector<DgVolume*> selected;
		for (DgVolume* vol : DgScene::instance().getSDFList())
		{
			if (vol && vol->mSelected)
				selected.push_back(vol);
		}

		if (ImGui::ImageButton("Union", DgUtil::toImTextureID(icon_tex_id[0]), ImVec2(64, 64), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selected.size() >= 2)
			{clock_t start, finish;
				DgVolume* result = DgBoolean::Boolean(selected, BooleanMode::Union, 128);
				if (result)
				{
					DgScene::instance().addSDFVolume(result);
					for (DgVolume* vol : selected)
						vol->mSelected = false;
					result->mSelected = true;
				}
			}
		}
		ImGui::SameLine();
		if (ImGui::ImageButton("Intersection", DgUtil::toImTextureID(icon_tex_id[1]), ImVec2(64, 64), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selected.size() >= 2)
			{
				DgVolume* result = DgBoolean::Boolean(selected, BooleanMode::Intersection, 64);
				if (result)
				{
					DgScene::instance().addSDFVolume(result);
					for (DgVolume* vol : selected) vol->mSelected = false;
					result->mSelected = true;
				}
			}
		}
		ImGui::SameLine();
		if (ImGui::ImageButton("Difference", DgUtil::toImTextureID(icon_tex_id[2]), ImVec2(64, 64), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selected.size() >= 2)
			{
				DgVolume* result = DgBoolean::Boolean(selected, BooleanMode::Difference, 64);
				if (result)
				{
					DgScene::instance().addSDFVolume(result);
					for (DgVolume* vol : selected) vol->mSelected = false;
					result->mSelected = true;
				}
			}
		}
	}

	if (ImGui::CollapsingHeader("Offset"))
	{
		// 선택된 볼륨 찾기
		DgVolume* selectedVol = nullptr;
		for (DgVolume* vol : DgScene::instance().getSDFList())
		{
			if (vol && vol->mSelected) {
				selectedVol = vol;
				break;
			}
		}

		if (selectedVol)
		{
			float offset = selectedVol->mOffset;

			ImGui::Text("Offset = %.2f", offset);

			if (ImGui::SliderFloat("##OffsetSlider", &offset, -2.0f, 1.0f, ""))
			{
				// 선택된 모든 볼륨에 적용
				for (DgVolume* vol : DgScene::instance().getSDFList())
				{
					if (vol && vol->mSelected)
					{
						vol->mOffset = offset;
					}
				}
			}

			// 리셋 버튼
			ImGui::SameLine();
			if (ImGui::Button("Reset"))
			{
				for (DgVolume* vol : DgScene::instance().getSDFList())
				{
					if (vol && vol->mSelected)
						vol->mOffset = 0.0f;
				}
			}
		}
		else
		{
			ImGui::TextDisabled("No volume selected");
		}
	}

	if (ImGui::CollapsingHeader("Sweeping"))
	{
		// 선택된 볼륨 확인
		DgVolume* selectedVol = nullptr;
		for (DgVolume* vol : DgScene::instance().getSDFList())
		{
			if (vol && vol->mSelected) {
				selectedVol = vol;
				break;
			}
		}

		if (ImGui::ImageButton("create_crv", DgUtil::toImTextureID(icon_tex_id[3]), ImVec2(84, 84), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if(selectedVol)
				DgScene::instance().enterTrajectoryMode(true);
		}

		ImGui::SameLine();
		if (ImGui::ImageButton("create_polyline", DgUtil::toImTextureID(icon_tex_id[4]), ImVec2(84, 84), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selectedVol) {
				DgScene::instance().enterTrajectoryMode(false);
			}
		}

		ImGui::Separator();
		ImGui::Text("Auto-generated Curves:");

		// Linear 
		if (ImGui::ImageButton("create_linear", DgUtil::toImTextureID(icon_tex_id[5]), ImVec2(84, 84), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selectedVol) {
				// 볼륨 중심 계산
				glm::vec3 center = selectedVol->getCenter();

				// 직선 궤적 생성: 중심에서 X축으로 5만큼 이동
				DgScene::instance().mTrajectory.generateLinear(center, center + glm::vec3(20.0f, 0.0f, 0.0f));
				DgScene::instance().mDrawingVolume = selectedVol;
				DgScene::instance().mAutoGenerated = true;
				DgScene::instance().setEditMode(EditMode::Trajectory);

				std::cout << "직선 궤적 생성 완료" << std::endl;
			}
		}
		ImGui::SameLine();

		// Bezier 
		if (ImGui::ImageButton("create_Curve", DgUtil::toImTextureID(icon_tex_id[6]), ImVec2(84, 84), ImVec2(0, 1), ImVec2(1, 0)))
		{
			if (selectedVol) {
				glm::vec3 center = selectedVol->getCenter();
				DgScene::instance().mTrajectory.generateCurve(center);
				DgScene::instance().mDrawingVolume = selectedVol;
				DgScene::instance().mAutoGenerated = true;
				DgScene::instance().setEditMode(EditMode::Trajectory);
				std::cout << "베지어 곡선 궤적 생성 완료" << std::endl;
			}
		}

		if (DgScene::instance().getEditMode() == EditMode::Trajectory)
		{
			ImGui::Text("Rotate: W / A / S / D");
		}

		DgTrajectory& traj = DgScene::instance().mTrajectory;

		if (!traj.controlPoints.empty())
		{
			ImGui::Separator();
			ImGui::Text("Curve Rotation");

			static glm::vec3 startEuler(0.f);  // degrees
			static glm::vec3 endEuler(0.f);

			bool changed = false;
			changed |= ImGui::SliderFloat3("Start (deg)", glm::value_ptr(startEuler), -180.f, 180.f);
			changed |= ImGui::SliderFloat3("End   (deg)", glm::value_ptr(endEuler), -180.f, 180.f);

			if (changed)
			{
				traj.controlPoints[0].rotation = glm::quat(glm::radians(startEuler));
				traj.controlPoints[3].rotation = glm::quat(glm::radians(endEuler));
				traj.rebuild();  // 슬라이더 움직일 때마다 frames 재생성
			}
		}

		if (traj.size() >= 2)
		{
			ImGui::Separator();
			ImGui::Text("Trajectory: %d frames", (int)traj.size());

			// 해상도 설정
			static int sweepResolution = 128;
			ImGui::SliderInt("Resolution", &sweepResolution, 64, 512);

			// 타임 스텝 설정
			static int timeSteps = 100;
			ImGui::SliderInt("sampling", &timeSteps, 20, 500);

			// Sweep 버튼 (기존 Stamping)
			if (ImGui::Button("Stamping CPU", ImVec2(-1,0)))
			{
				DgVolume* brush = DgScene::instance().mDrawingVolume;
				if (brush)
				{
					DgVolume* swept = DgSweep::generateSweptVolume(
						brush, traj, sweepResolution, timeSteps, false
					);

					if (swept)
					{
						DgSweep::fastSweeping(swept);
						DgScene::instance().addSDFVolume(swept);
						DgScene::instance().mSavedTrajectories.push_back(traj);
						swept->mSelected = true;
						brush->mSelected = false;
						DgScene::instance().exitTrajectoryMode();
						std::cout << "Swept Volume 생성 완료 (CPU)" << std::endl;
					}
				}
			}

			// GPU 버전 버튼
			if (ImGui::Button("Stamping GPU", ImVec2(-1, 0)))
			{
				DgVolume* brush = DgScene::instance().mDrawingVolume;
				if (brush)
				{
					DgVolume* swept = DgSweep::generateSweptVolume(
						brush, traj, sweepResolution, timeSteps, true
					);

					if (swept)
					{
						DgSweep::fastSweeping(swept);
						DgScene::instance().addSDFVolume(swept);
						DgScene::instance().mSavedTrajectories.push_back(traj);
						swept->mSelected = true;
						brush->mSelected = false;
						DgScene::instance().exitTrajectoryMode();
						std::cout << "Swept Volume 생성 완료 (GPU)" << std::endl;
					}
				}
			}

			// Brent CPU 버튼
			if (ImGui::Button("Brent CPU", ImVec2(-1, 0)))
			{
				DgVolume* brush = DgScene::instance().mDrawingVolume;
				if (brush)
				{
					DgVolume* swept = DgSweep::generateBrentCPU(
						brush, traj, sweepResolution, timeSteps
					);

					if (swept)
					{
						DgSweep::fastSweeping(swept);
						DgScene::instance().addSDFVolume(swept);
						DgScene::instance().mSavedTrajectories.push_back(traj);
						swept->mSelected = true;
						brush->mSelected = false;
						DgScene::instance().exitTrajectoryMode();
						std::cout << "Swept Volume 생성 완료 (Brent)" << std::endl;
					}
				}
			}

			// Brent GPU 버튼
			if (ImGui::Button("Brent GPU", ImVec2(-1, 0)))
			{
				DgVolume* brush = DgScene::instance().mDrawingVolume;
				if (brush)
				{
					DgVolume* swept = DgSweep::generateBrentGPU(
						brush, traj, sweepResolution, timeSteps
					);

					if (swept)
					{
						DgSweep::fastSweeping(swept);
						DgScene::instance().addSDFVolume(swept);
						DgScene::instance().mSavedTrajectories.push_back(traj);
						swept->mSelected = true;
						brush->mSelected = false;
						DgScene::instance().exitTrajectoryMode();
						std::cout << "Swept Volume 생성 완료 (Brent GPU)" << std::endl;
					}
				}
			}

			// 궤적 초기화 버튼
			if (ImGui::Button("Clear Trajectory", ImVec2(-1, 0)))
			{
				DgScene::instance().exitTrajectoryMode();
			}
		}

		ImGui::Separator();
		if (ImGui::Button("Fast Sweeping", ImVec2(-1, 0)))
		{
			DgVolume* brush = DgScene::instance().mDrawingVolume;
			if (brush)
			{
				DgSweep::fastSweeping(brush);
				std::cout << "Fast Sweeping 적용 (Drawing Volume)" << std::endl;
			}
		}
	}
}